# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Benchmarks

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  
  release:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Run benchmarks
      run: sbt clean 'project benchmarks;jmh:run -i 3 -wi 1 -f1 -t1'
