# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Release

on:
  push:
    tags:
      - 'release-*'

permissions:
  contents: read

jobs:
  
  release:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'sbt'
    - uses: sbt/setup-sbt@v1
    - name: Build archive
      run: sbt -J-Xss6M 'universal:packageBin'

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "app/target/universal/gen4s-app-*.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
